---
apache_app_listen_address:
  engine: 192.168.66.99
  engine_api: 192.168.66.99
  profile: 192.168.66.99
  authzserver: 192.168.66.99
  authz_admin: 192.168.66.99
  authz_playground: 192.168.66.99
  mujina_idp: 192.168.66.99
  mujina_sp: 192.168.66.99
  serviceregistry: 192.168.66.99
  static: 192.168.66.99
  teams: 192.168.66.99
  voot: 192.168.66.99
  pdp: 192.168.66.99
  welcome: 192.168.66.99
  oidc: 192.168.66.99
  oidcng: 192.168.66.99
  aa: 192.168.66.99
  metadata: 192.168.66.99
  manage: 192.168.66.99
  kibana: 192.168.66.99
  stats: 192.168.66.99

mongo_primary: True
