---
- name: Check if target dir exists
  stat:
    path: "{{ profile_current_release_symlink }}"
    follow: no
  register: profile_dir

- name: Download current version
  get_url:
    url: "{{ profile_download_url }}"
    dest: "{{ profile_build_path }}"
  register: profile_download

- name: Unpack current version
  unarchive:
    src: "{{ profile_build_path }}"
    dest: "{{ openconext_releases_dir }}"
    copy: no
  when:
    - profile_download.changed or profile_dir.stat.lnk_source != profile_release_dir

- name: Activate new Profile release
  file:
    src: "{{ profile_release_dir }}"
    dest: "{{ profile_current_release_symlink }}"
    state: link
  notify:
    - "restart httpd"
    - "restart php-fpm"
  when:
    - profile_download.changed or profile_dir.stat.lnk_source != profile_release_dir
