springapp_artifact_id: metadata-exporter
springapp_artifact_type: jar
springapp_artifact_group_dir: /org/openconext
springapp_version: "{{ metadata_exporter_version }}"
springapp_snapshot_timestamp: "{{ metadata_exporter_snapshot_timestamp }}"
springapp_dir: "{{ metadata_exporter_dir }}"
springapp_user: metadata-exporter
springapp_service_name: metadata-exporter
springapp_jar: "{{ metadata_exporter_jar }}"
springapp_tcpport: "{{ springapp_tcpport_error_handling }}"
springapp_local_jar: "{{ metadata_exporter_local_jar }}"
springapp_heapsize: 512m
springapp_random_source: "file:///dev/urandom"
