springapp_artifact_id: oidc-playground-server
springapp_artifact_type: jar
springapp_artifact_group_dir: org.openconext
springapp_version: "{{ oidc_playground_server_version }}"
springapp_snapshot_timestamp: "{{ oidc_playground_server_snapshot_timestamp }}"
springapp_dir: "{{ oidc_playground_dir }}"
springapp_user: oidc-playground
springapp_service_name: oidc-playground
springapp_jar: "{{ oidc_playground_jar }}"
springapp_tcpport: 9399
springapp_local_jar: "{{ oidc_playground_local_jar }}"
springapp_heapsize: "512m"
springapp_random_source: "file:///dev/urandom"
