---
- name: Create user
  user: name=metadata-exporter system=yes home={{ metadata_exporter_dir }} shell=/sbin/nologin

- name: Copy systemd service file
  template: src=templates/spring-boot.service.j2 dest=/etc/systemd/system/{{ springapp_service_name }}.service
  notify:
    - "systemctl daemon-reload"
    - "restart metadata-exporter"

- name: Check presence of legacy init script
  stat: path=/etc/init.d/{{ springapp_service_name }}
  register: legacy_meta_present

- name: Stop metadata exporter when legacy init script is present
  service: name={{ springapp_service_name }} state=stopped
  when: legacy_meta_present.stat.exists

- name: Clean up legacy init script
  file: path=/etc/init.d/{{ springapp_service_name }} state=absent

- name: enable metadata-exporter service
  service: name=metadata-exporter enabled=yes

- name: Create logging directory
  file: path=/var/log/{{ springapp_service_name }} state=directory owner=metadata-exporter group=metadata-exporter mode=0755

- include: ../../../tasks/springbootapp/install-release.yml
  when: "metadata_exporter_snapshot_timestamp == '' and metadata_exporter_local_jar == ''"

- include: ../../../tasks/springbootapp/install-snapshot.yml
  when: "metadata_exporter_snapshot_timestamp != '' and metadata_exporter_local_jar == ''"

- include: ../../../tasks/springbootapp/install-local.yml
  when: "metadata_exporter_local_jar != ''"

- name: Copy logging config
  template: src=logback.xml.j2 dest={{ metadata_exporter_dir }}/logback.xml owner=metadata-exporter group=metadata-exporter mode=0740
  notify: restart metadata-exporter

- name: Copy javascripts client
  template: src=javascript_error_registrations.json.j2 dest={{ metadata_exporter_dir }}/javascript_error_registrations.json owner=metadata-exporter group=metadata-exporter mode=0740
  notify: restart metadata-exporter

- name: Copy application config
  template: src=application.properties.j2 dest={{ metadata_exporter_dir }}/application.properties owner=metadata-exporter group=metadata-exporter mode=0740
  notify: restart metadata-exporter

- name: copy apache config
  template: src=metadata_exporter.conf.j2 dest=/etc/httpd/conf.d/metadata_exporter.conf
  notify: reload httpd

- meta: flush_handlers

- name: ensure the service is started
  service: name=metadata-exporter enabled=yes state=started
  ignore_errors: true
