springapp_artifact_id: attribute-mapper
springapp_artifact_type: jar
springapp_artifact_group_dir: /org/openconext
springapp_version: "{{ attribute_mapper_version }}"
springapp_snapshot_timestamp: "{{ attribute_mapper_snapshot_timestamp }}"
springapp_dir: "{{ attribute_mapper_dir }}"
springapp_user: attribute-mapper
springapp_service_name: attribute-mapper
springapp_jar: "{{ attribute_mapper_jar }}"
springapp_tcpport: 9292
springapp_local_jar: "{{ attribute_mapper_local_jar }}"
springapp_heapsize: "128m"
springapp_random_source: "file:///dev/urandom"
