springapp_artifact_id: aa-server
springapp_artifact_type: jar
springapp_artifact_group_dir: /org/openconext
springapp_version: "{{ aa_version }}"
springapp_snapshot_timestamp: "{{ aa_snapshot_timestamp }}"
springapp_dir: "{{ aa_dir }}"
springapp_user: aa
springapp_service_name: aa
springapp_jar: "{{ aa_jar }}"
springapp_tcpport: 9198
springapp_local_jar: "{{ aa_local_jar }}"
springapp_heapsize: "512m"
springapp_random_source: "file:///dev/urandom"
