appname: "azuremfa"
vhost_name: "{{ appname }}.{{ base_domain }}"
loadbalancingport: "411"
appversion: "{{ azuremfa_version }}"
appversion_sha: "{{ azuremfa_version_sha }}"
stepup_gh_appname: "Azure-MFA"
current_release_symlink: "/opt/openconext/OpenConext-{{ appname }}" 
current_release_appdir: "{{current_release_symlink }}-{{ appversion }}" 
current_release_config_file_dir_name: "{{ current_release_appdir }}/app/files"
current_release_config_dir_name: "{{ current_release_appdir }}/config/packages"
gssp_idp_private_key: "{{ lookup('file', inventory_dir+'/files/certs/stepup/azuremfa_idp.key') }}"
