---
appname: "selfservice"
vhost_name: "sa.{{ base_domain }}"
loadbalancingport: "415"
appversion: "{{ selfservice_version }}"
appversion_sha: "{{ selfservice_version_sha }}"
stepup_gh_appname: "SelfService"
current_release_symlink: "/opt/openconext/OpenConext-{{ appname }}"
current_release_appdir: "{{ current_release_symlink }}-{{ appversion }}"
current_release_config_file_dir_name: "{{ current_release_appdir }}/app/files"
current_release_config_dir_name: "{{ current_release_appdir }}/config/legacy"
current_release_config_file_dir_name_in_config: "{{ current_release_config_file_dir_name }}"
gssp_sp_private_key: "{{ lookup('file', inventory_dir+'/files/certs/stepup/selfservice_gssp_sp.key') }}"
stepup_saml_sp_privatekey: "{{ lookup('file', inventory_dir+'/files/certs/stepup/selfservice_saml_sp.key') }}"
gateway_saml_idp_publickey: "{{ lookup('file', inventory_dir+'/files/certs/stepup/gateway_saml_idp.crt') }}"
gateway_gssp_idp_publickey: "{{ lookup('file', inventory_dir+'/files/certs/stepup/gateway_gssp_idp.crt') }}"
fpmmemory: 128M
