---
attribute_aggregation_dir: /opt/attribute-aggregation
attribute_aggregation_version: ''
attribute_aggregation_snapshot_timestamp: ''
attribute_aggregation_local_jar: ''
attribute_aggregation_jar: attribute-aggregation-current.jar
attribute_aggregation_random_source: 'file:///dev/urandom'
attribute_aggregation_pseudo_mail_postfix: surfconext.nl
attribute_aggregation_pseudo_emails_retention_days_period: 90
aa_cronjobmaster: true
