---
apache_app_listen_address:
  engine: 192.168.66.79
  engine_api: 192.168.66.79
  profile: 192.168.66.79
  authzserver: 192.168.66.79
  authz_admin: 192.168.66.79
  authz_playground: 192.168.66.79
  grouper: 192.168.66.79
  mujina_idp: 192.168.66.79
  mujina_sp: 192.168.66.79
  serviceregistry: 192.168.66.79
  static: 192.168.66.79
  teams: 192.168.66.79
  voot: 192.168.66.79
  pdp: 192.168.66.79
  aa: 192.168.66.79
  welcome: 192.168.66.79
  oidc: 192.168.66.79
  aa: 192.168.66.79
  metadata_exporter: 192.168.66.79
  attribute_mapper: 192.168.66.79

