---
apache_app_listen_address:
  authzserver: 145.100.191.136
  authz_admin: 145.100.191.136
  authz_playground: 145.100.191.136
  grouper: 145.100.191.136
  teams: 145.100.191.136
  voot: 145.100.191.136
  aa: 145.100.191.136
