---
apache_app_listen_address:
  authzserver: 145.100.191.135
  authz_admin: 145.100.191.135
  authz_playground: 145.100.191.135
  grouper: 145.100.191.135
  teams: 145.100.191.135
  voot: 145.100.191.135
  aa: 145.100.191.135
