springapp_artifact_id: authz-admin
springapp_artifact_type: jar
springapp_artifact_group_dir: /org/openconext
springapp_version: "{{ authz_admin_version }}"
springapp_snapshot_timestamp: "{{ authz_admin_snapshot_timestamp }}"
springapp_dir: "{{ authz_admin_dir }}"
springapp_user: authz-admin
springapp_service_name: authz-admin
springapp_jar: "{{ authz_admin_jar }}"
springapp_tcpport: 9290
springapp_local_jar: "{{ authz_admin_local_jar }}"
springapp_heapsize: "128m"
springapp_random_source: "file:///dev/urandom"
