---
manage_dir: /opt/manage
manage_snapshot_timestamp: ''
manage_local_jar: ''
manage_jar: manage-current.jar
manage_random_source: 'file:///dev/urandom'
manage_cronjobmaster: false
manage_disclaimer_background_color: skyblue
manage_disclaimer_content: OC
manage_service_provider_feed_url: "http://mds.edugain.org/"
manage_exclude_edugain_imports_in_push: true
manage_show_oidc_rp_tab: false
manage_exclude_oidc_rp_imports_in_push: false
