# BASE: https://example.com
BASE: !ENV SATOSA_BASE

COOKIE_STATE_NAME: "SATOSA_STATE"
CONTEXT_STATE_DELETE: yes
#STATE_ENCRYPTION_KEY: "asdASD123"

cookies_samesite_compat:
  - ["SATOSA_STATE", "SATOSA_STATE_LEGACY"]

INTERNAL_ATTRIBUTES: "internal_attributes.yaml"

BACKEND_MODULES:
  - "plugins/backends/openid_backend.yaml"

FRONTEND_MODULES:
  - "plugins/frontends/saml2_frontend.yaml"
  - "plugins/frontends/ping_frontend.yaml"

MICRO_SERVICES:
  - "plugins/microservices/generate_attributes.yaml"
  - "plugins/microservices/regex_attributes.yaml"

LOGGING:
  version: 1
  formatters:
    simple:
      format: "[%(asctime)s] [%(levelname)s] [%(name)s.%(funcName)s] %(message)s"
  handlers:
    stdout:
      class: logging.StreamHandler
      stream: "ext://sys.stdout"
      level: INFO
      formatter: simple
    syslog:
      class: logging.handlers.SysLogHandler
      address: "/dev/log"
      level: INFO
      formatter: simple
    debug_file:
      class: logging.FileHandler
      filename: satosa-debug.log
      encoding: utf8
      level: INFO
      formatter: simple
    error_file:
      class: logging.FileHandler
      filename: satosa-error.log
      encoding: utf8
      level: ERROR
      formatter: simple
    info_file:
      class: logging.handlers.RotatingFileHandler
      filename: satosa-info.log
      encoding: utf8
      maxBytes: 10485760 # 10MB
      backupCount: 20
      level: INFO
      formatter: simple
  loggers:
    satosa:
      level: INFO
    saml2:
      level: INFO
    oidcendpoint:
      level: INFO
    pyop:
      level: INFO
    oic:
      level: INFO
  root:
    level: INFO
    handlers:
      - stdout
